# Change these first
owner: FujaTyping # Your GitHub organization or username, where this repository lives
repo: Upptime # The name of this repository

sites:
  - name: Personal Website
    url: https://dfujatyping.web.app/
  - name: Shop Website
    url: https://shopdfujatyping.web.app/
  - name: Link Portal
    url: https://portal-azure-rho.vercel.app/
  - name: Envision Project
    url: https://sma7tenvision.web.app/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: x.siraphop.me
  # baseUrl: /Upptime
  logoUrl: https://raw.githubusercontent.com/FujaTyping/Upptime/master/assets/upptime-icon.svg
  name: Typing Upptime
  introTitle: Real-Time Monitoring
  introMessage: Monitor real-time performance, updates, and any service interruptions. We're committed to keeping everything running smoothly.
  i18n:
    footer: Made with ❤️ by FujaTyping
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
